# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/orangepi/Qt/gui_qt/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubWindow_talking(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 645)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 773, 464))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_6.addWidget(self.listWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.clear_btn.setMaximumSize(QtCore.QSize(100, 100))
        self.clear_btn.setStyleSheet("QPushButton {\n"
"    border-image: url(\"/home/orangepi/Qt/test111/img/清空.png\");\n"
"    border-radius:10px;\n"
"}")
        self.clear_btn.setText("")
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setMinimumSize(QtCore.QSize(40, 40))
        self.setting.setMaximumSize(QtCore.QSize(40, 40))
        self.setting.setStyleSheet("QPushButton {\n"
"    border-image: url(\"/home/orangepi/Qt/gui_qt/img/设置.png\");\n"
"    border-radius:10px;\n"
"}")
        self.setting.setText("")
        self.setting.setObjectName("setting")
        self.gridLayout_5.addWidget(self.setting, 0, 1, 1, 1)
        self.video = QtWidgets.QPushButton(self.centralwidget)
        self.video.setMinimumSize(QtCore.QSize(40, 40))
        self.video.setMaximumSize(QtCore.QSize(40, 40))
        self.video.setStyleSheet("QPushButton {\n"
"    border-image: url(\"/home/orangepi/Qt/gui_qt/img/视频播放.png\");\n"
"    border-radius:10px;\n"
"}")
        self.video.setText("")
        self.video.setObjectName("video")
        self.gridLayout_5.addWidget(self.video, 0, 2, 1, 1)
        self.pdf = QtWidgets.QPushButton(self.centralwidget)
        self.pdf.setMinimumSize(QtCore.QSize(40, 40))
        self.pdf.setMaximumSize(QtCore.QSize(40, 40))
        self.pdf.setStyleSheet("QPushButton {\n"
"    border-image: url(\"/home/orangepi/Qt/gui_qt/img/pdf.png\");\n"
"    border-radius:10px;\n"
"}")
        self.pdf.setText("")
        self.pdf.setObjectName("pdf")
        self.gridLayout_5.addWidget(self.pdf, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
